-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/Pw3qu7fzqJA5bTw
hhvvoB/FZDfOyTb8Oad+kD6sv/egCgYIKoZIzj0DAQehRANCAARCaSkiEVbwrlVx
E8dWRysmr3mGNaQ7V9TYdYvDNQMuAeD+pavMSNVdBYvv9/COOL+iiDROD6zfIGQu
BUQCmruc
-----END PRIVATE KEY-----